---
object_type: class
version: 1.0
object:
  attributes:
    description: 
    display_name: 
    name: Inventory
    type: 
    inherits: 
    visibility: 
    owner: 
  schema:
  - field:
      aetype: attribute
      name: inventory_name
      display_name: 
      datatype: string
      priority: 1
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
  - field:
      aetype: attribute
      name: credential_name
      display_name: 
      datatype: string
      priority: 2
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
  - field:
      aetype: method
      name: refresh_method
      display_name: 
      datatype: string
      priority: 3
      owner: 
      default_value: refresh_inventory
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
