---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: RedHat_template
    name: RedHat_template
    inherits: 
    description: 
  fields:
  - AcquireIPAddress:
      value: "/Demo/Service/Provisioning/FixedDialogs/FixedDialogs/ConfigureIP"
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - RegisterDHCP:
      value: "/Integration/PowerDNS/API/AddHostDNS"
  - RegisterAD:
      value: "/Integration/Ansible/Attributes/SetHostAttributes"
  - ActivateCMDB:
      value: "/System/CommonMethods/StateMachineMethods/Add_VM_To_Service"
